In [2]:
import tensorflow as tf
import numpy as np

print(tf.__version__)
print(np.__version__)

2.3.0
1.18.5


In [6]:
tf.random.set_seed(0)

In [10]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]

W1 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
W2 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
b = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))

learning_rate = tf.Variable(0.001)

for i in range(1000 + 1):
    with tf.GradientTape() as tape:
        hypo = W1 * x1_data + W2 * x2_data + b
        cost = tf.reduce_mean(tf.square(hypo - y_data))
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])
    W1.assign_sub(learning_rate * W1_grad)
    W2.assign_sub(learning_rate * W2_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
         print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
          i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))

    0 | 335.280823 |    -4.0663 |     1.1220 |  -6.065215
   50 |  76.037262 |    -0.8001 |     1.6209 |  -4.978779
  100 |  18.959263 |     0.7151 |     1.8781 |  -4.429109
  150 |   6.310240 |     1.4125 |     2.0104 |  -4.134423
  200 |   3.445082 |     1.7284 |     2.0768 |  -3.961648
  250 |   2.743659 |     1.8667 |     2.1075 |  -3.847750
  300 |   2.525401 |     1.9225 |     2.1184 |  -3.762738
  350 |   2.417754 |     1.9402 |     2.1181 |  -3.692262
  400 |   2.337300 |     1.9403 |     2.1114 |  -3.629400
  450 |   2.264998 |     1.9325 |     2.1008 |  -3.570778
  500 |   2.196328 |     1.9213 |     2.0881 |  -3.514729
  550 |   2.130126 |     1.9085 |     2.0741 |  -3.460409
  600 |   2.066037 |     1.8953 |     2.0595 |  -3.407385
  650 |   2.003917 |     1.8819 |     2.0444 |  -3.355424
  700 |   1.943679 |     1.8686 |     2.0293 |  -3.304398
  750 |   1.885258 |     1.8555 |     2.0141 |  -3.254230
  800 |   1.828595 |     1.8425 |     1.9990 |  -3.204873
  850 |   1.77

In [16]:
x_data = [
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1,2), -1.0, 1.0))
b = tf.Variable(tf.random.uniform((1,), -1.0, 1.0))

learning_rate = tf.Variable(0.001)

for i in range(1000 + 1):
    with tf.GradientTape() as tape:
        hypo = tf.matmul(W, x_data) + b
        cost = tf.reduce_mean(tf.square(hypo - y_data))
        
        W_grad, b_grad = tape.gradient(cost, [W,b])
        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], b.numpy()[0]))

    0 |  25.972300 |    -0.9515 |     0.0227 |   0.600074
   50 |   6.070779 |    -0.0653 |     0.2696 |   0.888581
  100 |   1.597466 |     0.3474 |     0.4153 |   1.021349
  150 |   0.567457 |     0.5400 |     0.5039 |   1.078805
  200 |   0.317824 |     0.6306 |     0.5597 |   1.099501
  250 |   0.250031 |     0.6742 |     0.5960 |   1.102061
  300 |   0.226705 |     0.6960 |     0.6205 |   1.095580
  350 |   0.215147 |     0.7080 |     0.6379 |   1.084555
  400 |   0.207104 |     0.7156 |     0.6507 |   1.071247
  450 |   0.200309 |     0.7211 |     0.6607 |   1.056813
  500 |   0.194068 |     0.7258 |     0.6688 |   1.041862
  550 |   0.188148 |     0.7301 |     0.6758 |   1.026716
  600 |   0.182457 |     0.7341 |     0.6819 |   1.011554
  650 |   0.176958 |     0.7381 |     0.6875 |   0.996476
  700 |   0.171634 |     0.7420 |     0.6928 |   0.981537
  750 |   0.166473 |     0.7459 |     0.6978 |   0.966768
  800 |   0.161468 |     0.7497 |     0.7026 |   0.952189
  850 |   0.15

In [4]:
#bias 추가
x_data = [
    [1., 1., 1., 1., 1.],
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data = [1, 2, 3, 4, 5]

#bias 삭제
W = tf.Variable(tf.random.uniform((1, 3), -1.0, 1.0))

learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

for i in range(1000 + 1):
    with tf.GradientTape() as tape:
        hypo = tf.matmul(W, x_data)
        cost = tf.reduce_mean(tf.square(hypo - y_data))
    grads = tape.gradient(cost, [W])
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W]))
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |  20.821461 |    -0.9113 |    -0.3731 |     0.5707
   50 |   4.728793 |    -0.6296 |     0.4178 |     0.7869
  100 |   1.114711 |    -0.4884 |     0.7831 |     0.9118
  150 |   0.286174 |    -0.4154 |     0.9507 |     0.9852
  200 |   0.089094 |    -0.3757 |     1.0266 |     1.0291
  250 |   0.039149 |    -0.3527 |     1.0602 |     1.0555
  300 |   0.025114 |    -0.3382 |     1.0745 |     1.0713
  350 |   0.020492 |    -0.3280 |     1.0801 |     1.0807
  400 |   0.018589 |    -0.3202 |     1.0817 |     1.0862
  450 |   0.017563 |    -0.3138 |     1.0815 |     1.0891
  500 |   0.016855 |    -0.3081 |     1.0807 |     1.0905
  550 |   0.016276 |    -0.3028 |     1.0796 |     1.0908
  600 |   0.015758 |    -0.2979 |     1.0784 |     1.0906
  650 |   0.015272 |    -0.2932 |     1.0771 |     1.0899
  700 |   0.014808 |    -0.2886 |     1.0759 |     1.0890
  750 |   0.014360 |    -0.2841 |     1.0747 |     1.0880
  800 |   0.013928 |    -0.2798 |     1.0736 |     1.0869
  850 |   0.01

In [7]:
#bias없이, optimizer 사용

X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random.normal((2, 1)))
b = tf.Variable(tf.random.normal((1,)))

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

n_epoch = 1000 + 1
print("epoch | cost")
for i in range(n_epoch):
    with tf.GradientTape() as tape:
        hypo = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(hypo - y))
    grads = tape.gradient(cost, [W, b])
    #W, b update
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
    if i % 50 == 0:
        print("{:5} | {:10.6f}".format(i, cost.numpy()))

epoch | cost
    0 |   7.591746
   50 |   0.061465
  100 |   0.042024
  150 |   0.028732
  200 |   0.019645
  250 |   0.013431
  300 |   0.009183
  350 |   0.006278
  400 |   0.004293
  450 |   0.002935
  500 |   0.002007
  550 |   0.001372
  600 |   0.000938
  650 |   0.000641
  700 |   0.000438
  750 |   0.000300
  800 |   0.000205
  850 |   0.000140
  900 |   0.000096
  950 |   0.000066
 1000 |   0.000045


In [11]:
#matrix 없이 예측
tf.random.set_seed(0)

x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

w1 = tf.Variable(tf.random.normal((1,)))
w2 = tf.Variable(tf.random.normal((1,)))
w3 = tf.Variable(tf.random.normal((1,)))
b  = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

for i in range(1000 + 1):
    with tf.GradientTape() as tape:
        hypo = w1 * x1 + w2 * x2 + w3 *x3 + b
        cost = tf.reduce_mean(tf.square(hypo - Y))
        w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
        
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |   11325.9121
   50 |     135.3618
  100 |      11.1817
  150 |       9.7940
  200 |       9.7687
  250 |       9.7587
  300 |       9.7489
  350 |       9.7389
  400 |       9.7292
  450 |       9.7194
  500 |       9.7096
  550 |       9.6999
  600 |       9.6903
  650 |       9.6806
  700 |       9.6709
  750 |       9.6612
  800 |       9.6517
  850 |       9.6421
  900 |       9.6325
  950 |       9.6229
 1000 |       9.6134


In [13]:
#matrix를 사용하여 예측

data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

#slicing으로 x, y를 분리
#[행, 열]
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

#hypothesis
def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epoch + 1):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))
    W_grad, b_grad = tape.gradient(cost, [W, b])
     
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |  9563.7852
  100 |     4.5003
  200 |     3.3124
  300 |     3.3014
  400 |     3.2907
  500 |     3.2800
  600 |     3.2693
  700 |     3.2587
  800 |     3.2482
  900 |     3.2378
 1000 |     3.2274


In [14]:
W.numpy()

array([[ 1.8618126 ],
       [ 0.53110343],
       [-0.36347008]], dtype=float32)

In [15]:
b.numpy()

array([-0.57494545], dtype=float32)

In [16]:
Y

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [17]:
predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()

array([[182.14197],
       [173.78386]], dtype=float32)