In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1. 과거의 데이버 준비 (iris)
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(path)

# one-hot encoding
iris = pd.get_dummies(iris)

#독립, 종속 분리
독립 = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 2. 모델의 구조 만들기

X = tf.keras.layers.Input(shape = [4])
H = tf.keras.layers.Dense(5, activation = 'swish')(X)
H = tf.keras.layers.Dense(5, activation = 'swish')(X)
H = tf.keras.layers.Dense(5, activation = 'swish')(X)
Y = tf.keras.layers.Dense(3, activation = 'softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [9]:
# 3. 모델 학습(fit)
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0581 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0547 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0559 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0568 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0559 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0548 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0565 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0588 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0551 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0561 - accuracy: 0.9800


In [10]:
# 4. 모델 이용
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9999988e-01 1.6354014e-07 7.9225640e-20]
 [9.9999893e-01 1.1032050e-06 6.4581721e-18]
 [9.9999952e-01 4.4075506e-07 1.4112887e-18]
 [9.9999714e-01 2.8751599e-06 3.4034465e-17]
 [9.9999988e-01 1.4589837e-07 6.1733471e-20]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
